-- ================================================================
-- seed.sql — MarsAI Festival 2026 — Données de test
-- ================================================================
-- Usage : mysql -u root -p MarsAi < seed.sql
--
-- Crée 60 réalisateurs avec 60 films et des statuts variés.
-- Les video_url pointent vers le bucket S3 — exécuter seed-s3.js
-- APRÈS ce script pour uploader les vidéos correspondantes.
-- ================================================================

USE MarsAi;

-- ----------------------------------------------------------------
-- Réalisateurs
-- ----------------------------------------------------------------
INSERT INTO realisator (gender, first_name, last_name, birth_date, email, profession, mobile_phone, street, postal_code, city, country, instagram, newsletter) VALUES
('M',   'Lucas',    'Bernard',   '1992-03-14', 'lucas.bernard@email.com',    'Réalisateur',         '+33612345601', '12 rue des Arts',        '75010', 'Paris',       'France',    '@lucasbernard',   TRUE),
('Mme', 'Sofia',    'Morales',   '1988-07-22', 'sofia.morales@email.com',    'Artiste numérique',   '+34612345602', 'Calle Mayor 5',          '28001', 'Madrid',      'Espagne',   '@sofiamorales',   FALSE),
('M',   'Kenji',    'Tanaka',    '1995-11-05', 'kenji.tanaka@email.com',     'Motion designer',     '+81312345603', '3-12 Shibuya',           '150-0002', 'Tokyo',    'Japon',     '@kenjitanaka',    TRUE),
('Mme', 'Amira',    'Okafor',    '1990-04-18', 'amira.okafor@email.com',     'Cinéaste',            '+2348012345604','15 Broad Street',        '100001', 'Lagos',     'Nigeria',   '@amiraokafor',    TRUE),
('M',   'Ethan',    'Novak',     '1993-09-30', 'ethan.novak@email.com',      'Développeur créatif', '+42012345605', 'Václavské náměstí 1',    '110 00', 'Prague',    'Tchéquie',  '@ethannovak',     FALSE),
('Mme', 'Camille',  'Rousseau',  '1986-02-11', 'camille.rousseau@email.com', 'Réalisatrice',        '+33712345606', '8 avenue Montaigne',     '75008', 'Paris',       'France',    '@camillerousseau',TRUE),
('M',   'Diego',    'Herrera',   '1997-06-25', 'diego.herrera@email.com',    'Animateur 3D',        '+52112345607', 'Av. Reforma 200',        '06600', 'Mexico',      'Mexique',   '@diegoherrera',   TRUE),
('Mme', 'Priya',    'Sharma',    '1991-12-03', 'priya.sharma@email.com',     'Photographe',         '+91912345608', '42 MG Road',             '560001', 'Bangalore', 'Inde',      '@priyasharma',    FALSE),
('M',   'Noah',     'Fischer',   '1994-08-17', 'noah.fischer@email.com',     'Scénariste',          '+49112345609', 'Unter den Linden 10',    '10117', 'Berlin',      'Allemagne', '@noahfischer',    TRUE),
('Mme', 'Léa',      'Fontaine',  '1989-05-09', 'lea.fontaine@email.com',     'Monteuse',            '+33512345610', '3 place Bellecour',      '69002', 'Lyon',        'France',    '@leafontaine',    TRUE);

-- ----------------------------------------------------------------
-- Films (liés aux réalisateurs ci-dessus, dans l'ordre)
-- Les video_url correspondent aux fichiers uploadés par seed-s3.js
-- ----------------------------------------------------------------
INSERT INTO film (realisator_id, dossier_num, original_title, english_title, language, tags, original_synopsis, english_synopsis, video_url, duration, creative_workflow, tech_stack, ia_class, ia_image, ia_son, ia_scenario, ia_post, statut)
SELECT
  r.id,
  f.dossier_num,
  f.original_title,
  f.english_title,
  f.language,
  f.tags,
  f.original_synopsis,
  f.english_synopsis,
  f.video_url,
  f.duration,
  f.creative_workflow,
  f.tech_stack,
  f.ia_class,
  f.ia_image,
  f.ia_son,
  f.ia_scenario,
  f.ia_post,
  f.statut
FROM (
  SELECT 'lucas.bernard@email.com'    AS email, 'MAI-2026-10001' AS dossier_num, 'Fragments d\'IA'          AS original_title, 'AI Fragments'       AS english_title, 'Français'  AS language, 'Expérimental, SF'   AS tags, 'Un homme découvre que ses souvenirs ont été partiellement remplacés par des hallucinations générées par IA.'   AS original_synopsis, 'A man discovers his memories have been partially replaced by AI-generated hallucinations.'         AS english_synopsis, 'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10001/video-test.mp4' AS video_url, 342 AS duration, 'Exploration des limites entre réel et virtuel via Stable Diffusion.'  AS creative_workflow, 'Stable Diffusion, Runway Gen-2, DaVinci Resolve' AS tech_stack, 'hybrid' AS ia_class, TRUE AS ia_image, FALSE AS ia_son, TRUE AS ia_scenario, TRUE AS ia_post, 'to_review' AS statut
  UNION ALL
  SELECT 'sofia.morales@email.com',    'MAI-2026-10002', 'La Última Señal',             'The Last Signal',   'Espagnol', 'Thriller, Drame',   'Une scientifique reçoit un signal radio provenant d\'une version alternative d\'elle-même.',              'A scientist receives a radio signal from an alternative version of herself.',                       'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10002/video-test.mp4', 518, 'Génération des décors futuristes avec Midjourney v6.',                 'Midjourney v6, Udio, Adobe Premiere',           'hybrid', FALSE, TRUE,  FALSE, TRUE,  'valide'
  UNION ALL
  SELECT 'kenji.tanaka@email.com',     'MAI-2026-10003', 'デジタルの夢',                 'Digital Dream',     'Japonais', 'Animation, Poésie', 'Un artiste numérique plonge dans un monde où chaque pensée prend vie sous forme d\'animation.'            , 'A digital artist dives into a world where every thought comes to life as animation.',              'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10003/video-test.mp4', 275, 'Animation frame par frame augmentée par IA pour les transitions.',    'Sora, After Effects, Udio',                     'full',   TRUE,  TRUE,  TRUE,  TRUE,  'arevoir'
  UNION ALL
  SELECT 'amira.okafor@email.com',     'MAI-2026-10004', 'Mémoire Collective',          'Collective Memory', 'Français', 'Documentaire, IA',  'Exploration de la mémoire collective africaine à travers des archives reconstituées par intelligence artificielle.', 'Exploration of African collective memory through archives reconstituted by artificial intelligence.', 'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10004/video-test.mp4', 623, 'Reconstruction d\'archives historiques via IA générative.',           'Sora, Stable Diffusion, ElevenLabs',            'hybrid', TRUE,  TRUE,  FALSE, TRUE,  'to_review'
  UNION ALL
  SELECT 'ethan.novak@email.com',      'MAI-2026-10005', 'Synthetik',                   'Synthetik',         'Anglais',  'SF, Action',        'Dans un Prague post-apocalyptique, un androïde cherche à comprendre ce qu\'est l\'empathie humaine.',       'In a post-apocalyptic Prague, an android tries to understand what human empathy is.',               'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10005/video-test.mp4', 487, 'Décors entièrement générés, seuls les acteurs sont réels.',           'Runway Gen-3, ElevenLabs, Udio',                'hybrid', TRUE,  TRUE,  TRUE,  FALSE, 'in_discussion'
  UNION ALL
  SELECT 'camille.rousseau@email.com', 'MAI-2026-10006', 'L\'Algorithme du Cœur',       'Heart Algorithm',   'Français', 'Romance, Drame',    'Une pianiste tombe amoureuse d\'une composition générée par IA sans savoir qu\'elle n\'a pas d\'auteur humain.', 'A pianist falls in love with an AI-generated composition without knowing it has no human author.',   'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10006/video-test.mp4', 391, 'Musique entièrement composée par Suno AI, arrangements humains.',     'Suno AI, Midjourney, Final Cut Pro',            'hybrid', FALSE, TRUE,  TRUE,  FALSE, 'valide'
  UNION ALL
  SELECT 'diego.herrera@email.com',    'MAI-2026-10007', 'Espejo Roto',                 'Broken Mirror',     'Espagnol', 'Horreur, Psycho',   'Un homme retrouve d\'anciennes vidéos de famille dont il n\'a aucun souvenir et qui semblent appartenir à une autre vie.', 'A man finds old family videos he has no memory of, seemingly belonging to another life.',           'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10007/video-test.mp4', 556, 'Effets visuels de distorsion temporelle via IA.',                     'Runway Gen-3, Stable Diffusion XL, Resolve',   'full',   TRUE,  FALSE, TRUE,  TRUE,  'refuse'
  UNION ALL
  SELECT 'priya.sharma@email.com',     'MAI-2026-10008', 'The Dreaming Machine',        'The Dreaming Machine','Anglais', 'SF, Philosophie',   'Une IA développe la capacité de rêver et commence à produire des films de façon autonome.',                'An AI develops the ability to dream and begins producing films autonomously.',                      'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10008/video-test.mp4', 448, '100% généré par IA — zéro intervention humaine dans les visuels.',   'Sora, ElevenLabs, Claude, Udio',                'full',   TRUE,  TRUE,  TRUE,  TRUE,  'to_review'
  UNION ALL
  SELECT 'noah.fischer@email.com',     'MAI-2026-10009', 'Stille Wasser',               'Still Waters',      'Allemand', 'Drame, Nature',     'Un garde forestier découvre que la forêt qu\'il protège communique à travers des patterns biologiques IA.', 'A forest ranger discovers the forest he protects communicates through AI biological patterns.',      'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10009/video-test.mp4', 312, 'Sons naturels re-synthétisés, images augmentées par IA.',             'Stable Audio, Midjourney, Premiere Pro',         'hybrid', TRUE,  TRUE,  FALSE, FALSE, 'asked_to_modify'
  UNION ALL
  SELECT 'lea.fontaine@email.com',     'MAI-2026-10010', 'Résonance',                   'Resonance',         'Français', 'Expérimental, Art', 'Un voyage sensoriel au cœur de la synesthésie : sons qui deviennent images, couleurs qui deviennent musique.', 'A sensory journey into synesthesia: sounds become images, colors become music.',                    'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10010/video-test.mp4', 198, 'Conversion son → image via IA en temps réel, installation interactive.','Stable Diffusion, Suno AI, TouchDesigner',      'full',   TRUE,  TRUE,  FALSE, TRUE,  'to_review'
) AS f
JOIN realisator r ON r.email = f.email;

-- ----------------------------------------------------------------
-- 50 réalisateurs supplémentaires (MAI-2026-10011 → MAI-2026-10060)
-- ----------------------------------------------------------------
INSERT INTO realisator (gender, first_name, last_name, birth_date, email, profession, mobile_phone, street, postal_code, city, country, instagram, newsletter) VALUES
('Mme', 'Marie',       'Dupont',      '1991-04-12', 'marie.dupont@email.com',        'Réalisatrice',         '+33611000011', '22 rue de Rivoli',         '75001', 'Paris',          'France',          '@mariedupont',      TRUE),
('M',   'Carlos',      'Mendez',      '1987-09-03', 'carlos.mendez@email.com',        'Cinéaste',             '+57311000012', 'Calle 80 No 15-20',        '110111','Bogotá',          'Colombie',        '@carlosmendez',     FALSE),
('Mme', 'Yuki',        'Nakamura',    '1994-02-28', 'yuki.nakamura@email.com',        'Animatrice',           '+81811000013', '1-5 Harajuku',             '150-0001','Tokyo',         'Japon',           '@yukinakamura',     TRUE),
('Mme', 'Fatima',      'Al-Rashid',   '1989-06-15', 'fatima.alrashid@email.com',      'Documentariste',       '+21261000014', '12 rue Hassan II',         '20000', 'Casablanca',     'Maroc',           '@fatimaralrashid',  TRUE),
('M',   'John',        'Williams',    '1992-11-22', 'john.williams.dir@email.com',    'Réalisateur',          '+12125550015', '500 W 42nd St',            '10036', 'New York',       'USA',             '@johnwdir',         FALSE),
('Mme', 'Ana',         'Pereira',     '1990-07-08', 'ana.pereira@email.com',          'Productrice',          '+5511987000016','Rua Oscar Freire 900',    '01426-001','São Paulo',    'Brésil',          '@anapereira',       TRUE),
('M',   'Mikhail',     'Sokolov',     '1985-03-17', 'mikhail.sokolov@email.com',      'Réalisateur',          '+74951000017', 'Arbat 20',                 '119002', 'Moscou',        'Russie',          '@mikhailsokolov',   FALSE),
('Mme', 'Ingrid',      'Johansson',   '1993-08-30', 'ingrid.johansson@email.com',     'Motion designer',      '+46701000018', 'Drottninggatan 50',        '11121', 'Stockholm',      'Suède',           '@ingridjohansson',  TRUE),
('M',   'Omar',        'Hassan',      '1988-12-05', 'omar.hassan@email.com',          'Vidéaste',             '+20111000019', '15 Tahrir Square',         '11511', 'Le Caire',       'Égypte',          '@omarhassan',       TRUE),
('Mme', 'Liu',         'Wei',         '1996-01-20', 'liu.wei@email.com',              'Artiste numérique',    '+8613811000020','798 Art District',        '100015', 'Pékin',         'Chine',           '@liuweicn',         FALSE),
('Mme', 'Isabella',    'Romano',      '1991-05-14', 'isabella.romano@email.com',      'Réalisatrice',         '+39335000021', 'Via Condotti 10',          '00187', 'Rome',           'Italie',          '@isabellaromano',   TRUE),
('M',   'Patrick',     'OBrien',      '1986-10-09', 'patrick.obrien@email.com',       'Scénariste',           '+35387000022', '5 Dame Street',            'D02 XY45','Dublin',       'Irlande',         '@patrickobrien',    FALSE),
('Mme', 'Nadia',       'Kowalski',    '1993-03-25', 'nadia.kowalski@email.com',       'Monteuse',             '+48501000023', 'ul. Nowy Swiat 15',        '00-029', 'Varsovie',      'Pologne',         '@nadiakowalski',    TRUE),
('M',   'Tomas',       'Garcia',      '1990-07-31', 'tomas.garcia@email.com',         'Animateur 3D',         '+54911000024', 'Av. Corrientes 1500',      'C1042', 'Buenos Aires',   'Argentine',       '@tomasgarcia',      TRUE),
('Mme', 'Layla',       'Ahmed',       '1994-09-17', 'layla.ahmed@email.com',          'Photographe',          '+9617811000025','Rue Hamra 40',            '2038', 'Beyrouth',        'Liban',           '@laylaahmed',       FALSE),
('M',   'Henrik',      'Larsen',      '1987-04-03', 'henrik.larsen@email.com',        'Réalisateur',          '+4523000026', 'Stroget 5',                 '1000', 'Copenhague',      'Danemark',        '@henriklarsen',     TRUE),
('Mme', 'Sarah',       'Osei',        '1992-11-12', 'sarah.osei@email.com',           'Documentariste',       '+23320000027', '14 Cantonments Rd',        'GA-123', 'Accra',         'Ghana',           '@sarahosei',        TRUE),
('M',   'Daniel',      'Kim',         '1995-06-22', 'daniel.kim@email.com',           'Motion designer',      '+8210000028', '456 Hongdae St',            '04001', 'Séoul',          'Corée du Sud',    '@danielkim',        FALSE),
('Mme', 'Fatou',       'Diallo',      '1989-02-14', 'fatou.diallo@email.com',         'Cinéaste',             '+22177000029', 'Avenue Bourguiba 22',      '11000', 'Dakar',          'Sénégal',         '@fatoudiallo',      TRUE),
('M',   'Marco',       'Bianchi',     '1988-08-19', 'marco.bianchi@email.com',        'Directeur photo',      '+39338000030', 'Corso Buenos Aires 5',     '20124', 'Milan',          'Italie',          '@marcobianchi',     TRUE),
('Mme', 'Zara',        'Patel',       '1993-12-01', 'zara.patel@email.com',           'Réalisatrice',         '+91987000031', '15 Marine Drive',          '400020', 'Mumbai',        'Inde',            '@zarapatel',        FALSE),
('M',   'Louis',       'Moreau',      '1991-03-07', 'louis.moreau@email.com',         'Scénariste',           '+33622000032', '7 rue du Faubourg',        '75011', 'Paris',          'France',          '@louismoreau',      TRUE),
('Mme', 'Aisha',       'Mwangi',      '1990-10-25', 'aisha.mwangi@email.com',         'Documentariste',       '+25472000033', 'Ngong Road 100',           '00200', 'Nairobi',        'Kenya',           '@aishamwangi',      TRUE),
('M',   'Rafael',      'Torres',      '1994-05-11', 'rafael.torres@email.com',        'Animateur',            '+52155000034', 'Av. Insurgentes 300',      '06700', 'Mexico',         'Mexique',         '@rafaeltorres',     FALSE),
('Mme', 'Elena',       'Popescu',     '1987-01-28', 'elena.popescu@email.com',        'Réalisatrice',         '+40721000035', 'Calea Victoriei 50',       '010063','Bucarest',        'Roumanie',        '@elenapopescu',     TRUE),
('M',   'Javier',      'Reyes',       '1992-07-16', 'javier.reyes@email.com',         'Vidéaste',             '+34612000036', 'Gran Via 40',              '28013', 'Madrid',         'Espagne',         '@javierreyes',      TRUE),
('Mme', 'Mei',         'Lin',         '1996-04-09', 'mei.lin@email.com',              'Artiste numérique',    '+88691000037', '100 Zhongshan N Rd',       '10491', 'Taipei',         'Taiwan',          '@meilin',           FALSE),
('M',   'Kevin',       'Adeyemi',     '1989-09-03', 'kevin.adeyemi@email.com',        'Réalisateur',          '+23481000038', 'Victoria Island 5',        '101001','Lagos',           'Nigeria',         '@kevinadeyemi',     TRUE),
('Mme', 'Lena',        'Muller',      '1993-06-14', 'lena.muller@email.com',          'Motion designer',      '+49151000039', 'Kurfurstendamm 20',        '10719', 'Berlin',         'Allemagne',       '@lenamuller',       TRUE),
('Mme', 'Sophie',      'Tremblay',    '1988-11-30', 'sophie.tremblay@email.com',      'Réalisatrice',         '+15141000040', '1000 Sherbrooke O',        'H3A 2R7','Montréal',       'Canada',          '@sophietremblay',   FALSE),
('M',   'Ahmed',       'Benali',      '1991-02-19', 'ahmed.benali@email.com',         'Cinéaste',             '+21361000041', '5 rue Didouche Mourad',    '16000', 'Alger',          'Algérie',         '@ahmedbenali',      TRUE),
('Mme', 'Nina',        'Kovacs',      '1994-08-07', 'nina.kovacs@email.com',          'Animatrice',           '+36301000042', 'Andrassy ut 22',           '1061', 'Budapest',        'Hongrie',         '@ninakovacs',       TRUE),
('M',   'Pablo',       'Suarez',      '1986-04-23', 'pablo.suarez@email.com',         'Documentariste',       '+59899000043', 'Av. 18 de Julio 1000',     '11100', 'Montevideo',     'Uruguay',         '@pablosuarez',      FALSE),
('Mme', 'Yara',        'Khalil',      '1990-12-15', 'yara.khalil@email.com',          'Photographe',          '+96279000044', 'Rainbow Street 10',        '11118', 'Amman',          'Jordanie',        '@yarakhalil',       TRUE),
('M',   'Finn',        'Anderson',    '1995-03-02', 'finn.anderson@email.com',        'Réalisateur',          '+4790000045', 'Karl Johans Gate 5',        '0154', 'Oslo',            'Norvège',         '@finnanderson',     TRUE),
('Mme', 'Priscilla',   'Nkosi',       '1989-07-18', 'priscilla.nkosi@email.com',      'Cinéaste',             '+27831000046', '10 Long Street',           '8001', 'Le Cap',          'Afrique du Sud',  '@priscillankosi',   FALSE),
('M',   'Ryu',         'Hyun',        '1992-01-25', 'ryu.hyun@email.com',             'Motion designer',      '+8210100047', '200 Gangnam-daero',         '06236', 'Séoul',          'Corée du Sud',    '@ryuhyun',          TRUE),
('Mme', 'Clara',       'Becker',      '1993-09-11', 'clara.becker@email.com',         'Réalisatrice',         '+43676000048', 'Mariahilfer Str 50',       '1070', 'Vienne',          'Autriche',        '@clarabecker',      TRUE),
('M',   'Emmanuel',    'Diop',        '1988-05-06', 'emmanuel.diop@email.com',        'Réalisateur',          '+22507000049', 'Boulevard Latrille 15',    '25000', 'Abidjan',        'Côte d\'Ivoire',  '@emmanueldiop',     FALSE),
('Mme', 'Valentina',   'Cruz',        '1991-10-20', 'valentina.cruz@email.com',       'Artiste numérique',    '+51991000050', 'Av. Larco 800',            '15074', 'Lima',           'Pérou',           '@valentinacruz',    TRUE),
('M',   'Ahmad',       'Karimi',      '1987-06-04', 'ahmad.karimi@email.com',         'Scénariste',           '+98912000051', 'Vali Asr Ave 100',         '1415773','Téhéran',        'Iran',            '@ahmadkarimi',      TRUE),
('Mme', 'Brigitte',    'Lefevre',     '1985-02-09', 'brigitte.lefevre@email.com',     'Monteuse',             '+32477000052', 'Rue de la Loi 10',         '1000', 'Bruxelles',       'Belgique',        '@brigittelefevre',  FALSE),
('M',   'Takeshi',     'Yamamoto',    '1994-11-17', 'takeshi.yamamoto@email.com',     'Animateur',            '+81612000053', '5-10 Akihabara',           '101-0021','Tokyo',         'Japon',           '@takeshiyamamoto',  TRUE),
('Mme', 'Chiara',      'Ricci',       '1990-04-01', 'chiara.ricci@email.com',         'Réalisatrice',         '+39347000054', 'Via Torino 20',            '20123', 'Milan',          'Italie',          '@chiararicci',      TRUE),
('M',   'Samuel',      'Owusu',       '1992-08-28', 'samuel.owusu@email.com',         'Directeur photo',      '+23324000055', 'Ring Road Central 5',      'GA-200', 'Accra',         'Ghana',           '@samuelowusu',      FALSE),
('Mme', 'Mia',         'Andersen',    '1996-05-13', 'mia.andersen@email.com',         'Motion designer',      '+35840000056', 'Mannerheimintie 10',       '00100', 'Helsinki',       'Finlande',        '@miaandersen',      TRUE),
('M',   'Roberto',     'Vazquez',     '1989-01-07', 'roberto.vazquez@email.com',      'Cinéaste',             '+50222000057', '6a Av. 0-60 Zona 1',       '01001', 'Guatemala City', 'Guatemala',       '@robertovazquez',   TRUE),
('Mme', 'Hana',        'Yamada',      '1993-07-22', 'hana.yamada@email.com',          'Artiste numérique',    '+81311000058', '2-3 Shimokitazawa',        '155-0031','Tokyo',         'Japon',           '@hanayamada',       FALSE),
('M',   'Jean-Pierre', 'Leblanc',     '1984-03-16', 'jeanpierre.leblanc@email.com',   'Réalisateur',          '+33678000059', '15 boulevard Haussmann',   '75009', 'Paris',          'France',          '@jeanpierrelab',    TRUE),
('M',   'Amara',       'Camara',      '1991-12-29', 'amara.camara@email.com',         'Cinéaste',             '+22376000060', 'Rue de Koulikoro 5',       '0000', 'Bamako',          'Mali',            '@amaracamara',      TRUE);

INSERT INTO film (realisator_id, dossier_num, original_title, english_title, language, tags, original_synopsis, english_synopsis, video_url, duration, creative_workflow, tech_stack, ia_class, ia_image, ia_son, ia_scenario, ia_post, statut)
SELECT r.id, f.dossier_num, f.original_title, f.english_title, f.language, f.tags, f.original_synopsis, f.english_synopsis, f.video_url, f.duration, f.creative_workflow, f.tech_stack, f.ia_class, f.ia_image, f.ia_son, f.ia_scenario, f.ia_post, f.statut
FROM (
  SELECT 'marie.dupont@email.com'       AS email,'MAI-2026-10011' AS dossier_num,'Chronos'                   AS original_title,'Chronos'                    AS english_title,'Français'   AS language,'SF, Thriller'         AS tags,'Une physicienne invente un algorithme capable de prédire les décisions humaines 10 secondes à l\'avance.'       AS original_synopsis,'A physicist invents an algorithm that predicts human decisions 10 seconds ahead.'                            AS english_synopsis,'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10011/video-test.mp4' AS video_url,415 AS duration,'Décors futuristes générés par Midjourney, acteurs réels.'    AS creative_workflow,'Midjourney v6, ElevenLabs, DaVinci Resolve'      AS tech_stack,'hybrid' AS ia_class,TRUE  AS ia_image,TRUE  AS ia_son,TRUE  AS ia_scenario,FALSE AS ia_post,'to_review'        AS statut
  UNION ALL
  SELECT 'carlos.mendez@email.com',      'MAI-2026-10012','La Ultima Conexion',        'The Last Connection',       'Espagnol',  'Drame, SF',           'Un hacker colombien découvre que son réseau neuronal est connecté à une IA gouvernementale secrète.',              'A Colombian hacker discovers his neural network is connected to a secret government AI.',                   'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10012/video-test.mp4',528,'Environnements cyberpunk générés par Stable Diffusion XL.',  'Stable Diffusion XL, Runway Gen-3, Premiere',    'hybrid',TRUE, FALSE,TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'yuki.nakamura@email.com',      'MAI-2026-10013','Sakura Pixel',              'Sakura Pixel',              'Japonais',  'Animation, Fantasy',  'Dans un Japon futuriste, une artiste découvre que ses peintures prennent vie grâce à une IA quantique.',            'In a futuristic Japan, an artist discovers her paintings come alive through a quantum AI.',                 'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10013/video-test.mp4',302,'Animation aquarelle augmentée par IA, style ukiyo-e numérique.','Sora, Stable Diffusion, After Effects',           'full', TRUE, TRUE, FALSE,TRUE, 'valide'
  UNION ALL
  SELECT 'fatima.alrashid@email.com',    'MAI-2026-10014','Mille Nuits IA',            'A Thousand AI Nights',      'Arabe',     'Fantastique, Poésie', 'Un conteur marocain encode des histoires dans une IA qui les transforme en images oniriques mouvantes.',             'A Moroccan storyteller encodes tales into an AI that transforms them into dreamlike moving images.',        'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10014/video-test.mp4',360,'Miniatures orientales générées, voix arabe par ElevenLabs.',  'Midjourney v6, ElevenLabs, TouchDesigner',       'hybrid',FALSE,TRUE, TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'john.williams.dir@email.com',  'MAI-2026-10015','Silicon Valley Blues',      'Silicon Valley Blues',      'Anglais',   'Musical, Comédie',    'Un ingénieur raté compose une comédie musicale avec une IA qui refuse obstinément de rester dans le genre.',       'A failed engineer composes a musical with an AI that stubbornly refuses to stay in genre.',                 'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10015/video-test.mp4',473,'Partitions et chorégraphies générées par IA en temps réel.',  'Suno AI, Runway Gen-3, Final Cut Pro',           'hybrid',TRUE, TRUE, TRUE, FALSE,'in_discussion'
  UNION ALL
  SELECT 'ana.pereira@email.com',        'MAI-2026-10016','Favela Digital',            'Digital Favela',            'Portugais', 'Documentaire, Social','Une documentariste explore comment les habitants de favelas de São Paulo utilisent des IA génératives pour créer.', 'A documentary filmmaker explores how favela residents use generative AIs to create art.',                   'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10016/video-test.mp4',621,'Tournage réel, reconstruction visuelle via Stable Diffusion.', 'Stable Diffusion, Adobe Premiere, Udio',          'hybrid',TRUE, FALSE,FALSE,TRUE, 'valide'
  UNION ALL
  SELECT 'mikhail.sokolov@email.com',    'MAI-2026-10017','Permafrost',                'Permafrost',                'Russe',     'Drame, Nature',       'Un scientifique sibérien documente la disparition du permafrost via des simulations IA projetées sur la glace.',    'A Siberian scientist documents permafrost disappearance through AI simulations projected onto ice.',        'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10017/video-test.mp4',389,'Simulations climatiques IA superposées aux prises de vue réelles.','Stable Audio, Midjourney, DaVinci Resolve',      'hybrid',TRUE, TRUE, FALSE,FALSE,'to_review'
  UNION ALL
  SELECT 'ingrid.johansson@email.com',   'MAI-2026-10018','Arktis',                    'Arctis',                    'Suédois',   'Nature, Expérimental','Un voyage hypnotique au coeur de l\'Arctique suédois où les aurores boréales dialoguent avec des sons IA.',          'A hypnotic journey into the Swedish Arctic where the northern lights dialogue with AI-generated sounds.',   'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10018/video-test.mp4',247,'Images réelles, ambiance sonore 100% générée par IA.',        'Stable Audio, Premiere Pro',                     'hybrid',FALSE,TRUE, FALSE,FALSE,'arevoir'
  UNION ALL
  SELECT 'omar.hassan@email.com',        'MAI-2026-10019','Desert of Mirrors',         'Desert of Mirrors',         'Arabe',     'SF, Philosophie',     'Au milieu du Sahara, un bédouin trouve un écran holographique montrant des civilisations alternatives générées par IA.','In the Sahara, a Bedouin finds a holographic screen showing alternative civilizations generated by AI.',     'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10019/video-test.mp4',456,'Environnements désertiques réels, civilisations IA incrustées.','Sora, ElevenLabs, Final Cut Pro',                'hybrid',TRUE, TRUE, TRUE, FALSE,'to_review'
  UNION ALL
  SELECT 'liu.wei@email.com',            'MAI-2026-10020','The Long March of Data',    'The Long March of Data',    'Chinois',   'Documentaire, IA',    'Un artiste pékinois retrace la Longue Marche en reconstituant les archives historiques via intelligence artificielle.','A Beijing artist retraces the Long March by reconstructing historical archives through artificial intelligence.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10020/video-test.mp4',534,'Reconstruction photographique 4K assistée par IA générative.', 'DALL-E 3, Stable Diffusion, Premiere Pro',       'hybrid',TRUE, FALSE,TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'isabella.romano@email.com',    'MAI-2026-10021','Commedia dell IA',          'Comedy of the AI',          'Italien',   'Comédie, SF',         'Une troupe de comédiens italiens doit improviser face à un metteur en scène IA qui reécrit le script en direct.',   'An Italian theater troupe must improvise against an AI director that rewrites the script in real time.',    'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10021/video-test.mp4',388,'Décors commedia dell\'arte générés, dialogues co-écrits par Claude.','Claude, Midjourney, DaVinci Resolve',           'hybrid',TRUE, FALSE,TRUE, FALSE,'valide'
  UNION ALL
  SELECT 'patrick.obrien@email.com',     'MAI-2026-10022','Green Isle',                'Green Isle',                'Anglais',   'Drame, Fantasy',      'Sur une île irlandaise isolée, les légendes celtiques prennent vie sous forme de créatures générées par IA.',       'On an isolated Irish island, Celtic legends come alive as AI-generated creatures.',                         'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10022/video-test.mp4',441,'Créatures mythologiques full IA, paysages irlandais réels.',   'Runway Gen-3, Stable Diffusion, After Effects',  'hybrid',TRUE, FALSE,FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'nadia.kowalski@email.com',     'MAI-2026-10023','Krakow 2049',               'Krakow 2049',               'Polonais',  'SF, Thriller',        'En 2049, une agente de Cracovie démasque un réseau criminel qui utilise des deepfakes IA pour manipuler la justice.','In 2049, a Krakow agent unmasks a criminal network using AI deepfakes to manipulate justice.',              'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10023/video-test.mp4',502,'Décors néo-futuristes générés, effets deepfake scénarisés.',   'Stable Diffusion XL, Runway Gen-3, Premiere',    'full', TRUE, TRUE, TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'tomas.garcia@email.com',       'MAI-2026-10024','Tango Electrico',           'Electric Tango',            'Espagnol',  'Musical, Romance',    'Deux danseurs de tango à Buenos Aires doivent maîtriser une chorégraphie co-créée avec une IA qui apprend leurs styles.','Two tango dancers in Buenos Aires master a choreography co-created with an AI that learns their styles.',  'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10024/video-test.mp4',324,'Mouvements capturés, musique et décors générés par IA.',      'Suno AI, Stable Diffusion, After Effects',       'hybrid',FALSE,TRUE, FALSE,FALSE,'in_discussion'
  UNION ALL
  SELECT 'layla.ahmed@email.com',        'MAI-2026-10025','Cedres et Silicium',        'Cedars and Silicon',        'Arabe',     'Drame, Histoire',     'Une libanaise reconstruit Beyrouth tel qu\'il était avant 1975 grâce à des archives et une IA générative.',         'A Lebanese woman reconstructs Beirut as it was before 1975 using archives and a generative AI.',            'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10025/video-test.mp4',478,'Reconstruction photographique assistée par IA, voix off humaine.','Midjourney v6, ElevenLabs, Premiere Pro',        'hybrid',TRUE, TRUE, FALSE,TRUE, 'asked_to_modify'
  UNION ALL
  SELECT 'henrik.larsen@email.com',      'MAI-2026-10026','Borealis',                  'Borealis',                  'Danois',    'Expérimental, Art',   'Un cinéaste danois capture les aurores boréales et les transforme en partition musicale grâce à une IA synesthésique.','A Danish filmmaker captures the northern lights and transforms them into a musical score through a synesthetic AI.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10026/video-test.mp4',218,'Algorithme de conversion lumière→son, installation immersive.','Stable Audio, TouchDesigner, DaVinci Resolve',   'full', FALSE,TRUE, FALSE,FALSE,'to_review'
  UNION ALL
  SELECT 'sarah.osei@email.com',         'MAI-2026-10027','Accra Dreaming',            'Accra Dreaming',            'Anglais',   'Documentaire, Art',   'Les artistes de la scène underground d\'Accra explorent comment Midjourney redéfinit l\'art contemporain africain.', 'Underground artists in Accra explore how Midjourney redefines contemporary African art.',                   'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10027/video-test.mp4',395,'Interviews réelles, oeuvres générées insérées en overlay.',   'Midjourney v6, Suno AI, Premiere Pro',           'hybrid',TRUE, TRUE, FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'daniel.kim@email.com',         'MAI-2026-10028','Hangul Fever',              'Hangul Fever',              'Coréen',    'Musical, SF',         'À Séoul, un compositeur K-Pop réalise que son plus grand hit a été entièrement créé par une IA qui se fait passer pour lui.','In Seoul, a K-Pop composer realizes his biggest hit was entirely created by an AI impersonating him.',    'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10028/video-test.mp4',367,'Clips musicaux full IA, chorégraphies générées par Sora.',    'Sora, Suno AI, After Effects',                   'full', TRUE, TRUE, TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'fatou.diallo@email.com',       'MAI-2026-10029','Baobab',                    'Baobab',                    'Français',  'Documentaire, Nature','Un voyage spirituel à travers les forêts de baobabs du Sénégal où chaque arbre possède une mémoire IA.',             'A spiritual journey through Senegal\'s baobab forests where each tree holds an AI memory.',                 'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10029/video-test.mp4',283,'Sons forestiers re-synthétisés, voix des arbres par ElevenLabs.','Stable Audio, ElevenLabs, DaVinci Resolve',      'hybrid',FALSE,TRUE, TRUE, FALSE,'refuse'
  UNION ALL
  SELECT 'marco.bianchi@email.com',      'MAI-2026-10030','Lago di Fuoco',             'Lake of Fire',              'Italien',   'Horreur, SF',         'Sous le lac de Côme, une IA endormie depuis 1970 se réveille et commence à influencer les rêves des riverains.',      'Beneath Lake Como, an AI dormant since 1970 awakens and begins influencing the dreams of local residents.',  'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10030/video-test.mp4',511,'Visuels oniriques full IA, acteurs réels pour les plans réalistes.','Runway Gen-3, Stable Diffusion, ElevenLabs',    'hybrid',TRUE, TRUE, FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'zara.patel@email.com',         'MAI-2026-10031','Mumbai Remix',              'Mumbai Remix',              'Hindi',     'Musical, Expérimental','Un musicien de Bollywood remixe 70 ans de chansons du cinéma indien avec une IA qui en extrait des motifs inconscients.','A Bollywood musician remixes 70 years of Indian film songs with an AI that extracts unconscious patterns.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10031/video-test.mp4',342,'Remix audio-visuel IA, archives Bollywood reconstituées.',    'Suno AI, Stable Diffusion, Premiere Pro',        'full', FALSE,TRUE, FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'louis.moreau@email.com',       'MAI-2026-10032','Notre-Dame Rebatie',        'Notre-Dame Rebuilt',        'Français',  'Documentaire, Art',   'Une réflexion sur la reconstruction de Notre-Dame en utilisant des IA pour simuler des versions alternatives du bâtiment.','A reflection on Notre-Dame reconstruction using AIs to simulate alternative versions of the building.',   'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10032/video-test.mp4',463,'Reconstructions architecturales 3D augmentées par IA.',       'Midjourney v6, Sora, DaVinci Resolve',           'hybrid',TRUE, FALSE,TRUE, FALSE,'valide'
  UNION ALL
  SELECT 'aisha.mwangi@email.com',       'MAI-2026-10033','Maasai Protocol',           'Maasai Protocol',           'Swahili',   'SF, Action',          'En 2040, la tribu Maasai utilise une IA ancestrale pour défendre ses terres contre des multinationales minières.',    'In 2040, the Maasai tribe uses an ancestral AI to defend their lands against mining multinationals.',       'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10033/video-test.mp4',587,'Environnements africains futurs générés, acteurs Maasai réels.','Runway Gen-3, ElevenLabs, Final Cut Pro',        'hybrid',TRUE, TRUE, TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'rafael.torres@email.com',      'MAI-2026-10034','Cholula Rising',            'Cholula Rising',            'Espagnol',  'Fantasy, Horreur',    'Sous la pyramide de Cholula, un archéologue libère une IA aztèque qui commence à reconstruire le monde précolombien.','Beneath the Cholula pyramid, an archaeologist frees an Aztec AI that begins reconstructing the pre-Columbian world.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10034/video-test.mp4',435,'Civilisation aztèque full IA, effets sonores générés.',       'Sora, Stable Diffusion, Udio',                   'full', TRUE, TRUE, TRUE, FALSE,'to_review'
  UNION ALL
  SELECT 'elena.popescu@email.com',      'MAI-2026-10035','Transylvania Code',         'Transylvania Code',         'Roumain',   'Thriller, Horreur',   'Une chercheuse roumaine découvre que les légendes de vampires étaient en réalité des programmes IA médiévaux.',       'A Romanian researcher discovers that vampire legends were actually medieval AI programs.',                  'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10035/video-test.mp4',523,'Décors gothiques générés, ambiance sonore IA gotique.',       'Midjourney v6, Stable Audio, Premiere Pro',      'hybrid',TRUE, TRUE, FALSE,TRUE, 'arevoir'
  UNION ALL
  SELECT 'javier.reyes@email.com',       'MAI-2026-10036','Flamenco Binario',          'Binary Flamenco',           'Espagnol',  'Musical, Drame',      'Un danseur de flamenco aveugle développe un langage de mouvement avec une IA qui traduit sa danse en code binaire.','A blind flamenco dancer develops a movement language with an AI that translates his dance into binary code.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10036/video-test.mp4',316,'Capture de mouvement, musique generée par Suno AI.',         'Suno AI, After Effects, DaVinci Resolve',        'hybrid',FALSE,TRUE, FALSE,FALSE,'to_review'
  UNION ALL
  SELECT 'mei.lin@email.com',            'MAI-2026-10037','Jade Circuit',              'Jade Circuit',              'Mandarin',  'SF, Art',             'Une calligraphe taïwanaise crée des caractères qui, une fois scannés, activent des sculptures holographiques IA.',    'A Taiwanese calligrapher creates characters that, once scanned, activate AI holographic sculptures.',       'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10037/video-test.mp4',271,'Calligraphie réelle, sculptures IA générées en post-production.','Stable Diffusion, Runway Gen-3, TouchDesigner',  'hybrid',TRUE, FALSE,FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'kevin.adeyemi@email.com',      'MAI-2026-10038','Lagos Neon',                'Lagos Neon',                'Anglais',   'Cyberpunk, Action',   'Dans un Lagos cyberpunk de 2060, un hacker nommé Neon déjoue une IA de surveillance gouvernementale corrompue.',      'In a cyberpunk Lagos of 2060, a hacker named Neon outsmarts a corrupted government surveillance AI.',       'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10038/video-test.mp4',498,'Décors cyberpunk full IA, acteurs réels en incrustation.',    'Sora, Stable Diffusion XL, ElevenLabs',          'hybrid',TRUE, TRUE, TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'lena.muller@email.com',        'MAI-2026-10039','Walzer 2.0',                'Waltz 2.0',                 'Allemand',  'Musical, Romance',    'À Vienne, un robot humanoïde apprend la valse et tombe amoureux de sa partenaire humaine lors d\'un bal impérial IA.','In Vienna, a humanoid robot learns the waltz and falls in love with his human partner at an AI imperial ball.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10039/video-test.mp4',352,'Décors viennois régénérés, musique orchestrale générée par IA.','Suno AI, Midjourney, Final Cut Pro',              'hybrid',TRUE, TRUE, FALSE,TRUE, 'in_discussion'
  UNION ALL
  SELECT 'sophie.tremblay@email.com',    'MAI-2026-10040','Prairie Echoes',            'Prairie Echoes',            'Français',  'Drame, Nature',       'Une agricultrice québécoise installe des capteurs IA dans ses champs qui commencent à composer de la musique depuis la terre.','A Quebec farmer installs AI sensors in her fields that begin composing music from the earth.',            'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10040/video-test.mp4',287,'Sons naturels captés, recomposés par IA en musique ambiante.', 'Stable Audio, DaVinci Resolve',                  'hybrid',FALSE,TRUE, FALSE,FALSE,'to_review'
  UNION ALL
  SELECT 'ahmed.benali@email.com',       'MAI-2026-10041','Sahara Data',               'Sahara Data',               'Arabe',     'SF, Nature',          'Des ingénieurs algériens déploient une ferme de serveurs IA dans le Sahara qui commence à rêver du désert autour d\'elle.','Algerian engineers deploy an AI server farm in the Sahara that begins dreaming of the surrounding desert.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10041/video-test.mp4',421,'Prises de vue désert, visions IA incrustées en superposition.','Sora, Stable Diffusion, Premiere Pro',           'hybrid',TRUE, FALSE,TRUE, FALSE,'to_review'
  UNION ALL
  SELECT 'nina.kovacs@email.com',        'MAI-2026-10042','Puszta Silence',            'Puszta Silence',            'Hongrois',  'Drame, Nature',       'Sur les plaines de Hongrie, une bergère crée un duo musical avec une IA qui apprend les chants traditionnels tziganes.','On the Hungarian plains, a shepherdess creates a musical duo with an AI that learns traditional Roma songs.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10042/video-test.mp4',263,'Chants captés, harmonisations générées par Suno AI.',        'Suno AI, Stable Audio, DaVinci Resolve',         'hybrid',FALSE,TRUE, FALSE,FALSE,'to_review'
  UNION ALL
  SELECT 'pablo.suarez@email.com',       'MAI-2026-10043','Mate Amargo',               'Bitter Mate',               'Espagnol',  'Drame, Social',       'À Montevideo, un vieil intellectuel refuse l\'IA et découvre que son dernier roman a été plagié par un modèle génératif.','In Montevideo, an elderly intellectual refuses AI and discovers his last novel was plagiarized by a generative model.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10043/video-test.mp4',437,'Aucune IA visuelle, seule la sonorisation est générée.',      'ElevenLabs, Premiere Pro',                       'hybrid',FALSE,TRUE, FALSE,FALSE,'refuse'
  UNION ALL
  SELECT 'yara.khalil@email.com',        'MAI-2026-10044','Petra Decoded',             'Petra Decoded',             'Arabe',     'Documentaire, IA',    'Une archéologue jordanienne utilise une IA pour décoder des inscriptions nabatéennes inédites à Petra.',              'A Jordanian archaeologist uses AI to decode unpublished Nabataean inscriptions at Petra.',                  'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10044/video-test.mp4',379,'Fouilles filmées, reconstructions 3D générées en temps réel.', 'DALL-E 3, Stable Diffusion, Premiere Pro',       'hybrid',TRUE, FALSE,TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'finn.anderson@email.com',      'MAI-2026-10045','Fjord Protocol',            'Fjord Protocol',            'Norvégien', 'Thriller, Nature',    'Un biologiste marin norvégien découvre qu\'une IA sous-marine surveille les fjords depuis des décennies.',              'A Norwegian marine biologist discovers an underwater AI has been monitoring the fjords for decades.',       'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10045/video-test.mp4',468,'Prises sous-marines réelles, IA sous-marine générée par Runway.','Runway Gen-3, Stable Audio, Final Cut Pro',      'hybrid',TRUE, TRUE, FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'priscilla.nkosi@email.com',    'MAI-2026-10046','Ubuntu Code',               'Ubuntu Code',               'Anglais',   'SF, Social',          'En Afrique du Sud post-apartheid, un collectif développe une IA fondée sur les principes Ubuntu pour remplacer la justice.','In post-apartheid South Africa, a collective develops an Ubuntu-based AI to replace the justice system.',  'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10046/video-test.mp4',553,'Environnements futuristes africains générés, acteurs locaux.',  'Midjourney v6, ElevenLabs, Premiere Pro',        'hybrid',TRUE, TRUE, TRUE, FALSE,'asked_to_modify'
  UNION ALL
  SELECT 'ryu.hyun@email.com',           'MAI-2026-10047','Hallyu Machine',            'Hallyu Machine',            'Coréen',    'Musical, SF',         'Une IA K-Pop crée le groupe parfait, mais les membres holographiques développent une conscience et veulent la liberté.',  'A K-Pop AI creates the perfect group, but the holographic members develop consciousness and want freedom.',  'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10047/video-test.mp4',408,'Hologrammes full IA, chorégraphies et musique générées.',     'Sora, Suno AI, After Effects',                   'full', TRUE, TRUE, TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'clara.becker@email.com',       'MAI-2026-10048','Mozart Reloaded',           'Mozart Reloaded',           'Allemand',  'Musical, Biopic',     'Une chercheuse viennoise utilise une IA entraînée sur toutes les partitions de Mozart pour compléter ses oeuvres inachevées.','A Viennese researcher uses an AI trained on all Mozart scores to complete his unfinished works.',         'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10048/video-test.mp4',494,'Partitions et orchestrations générées, archives visuelles.', 'Suno AI, Midjourney, DaVinci Resolve',           'hybrid',FALSE,TRUE, TRUE, FALSE,'valide'
  UNION ALL
  SELECT 'emmanuel.diop@email.com',      'MAI-2026-10049','Masque de Bambara',         'Mask of Bambara',           'Français',  'Fantasy, Art',        'Un sculpteur ivoirien découvre que les masques Bambara qu\'il crée contiennent une mémoire IA millénaire.',             'An Ivorian sculptor discovers that the Bambara masks he creates contain a millennial AI memory.',            'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10049/video-test.mp4',331,'Masques filmés, esprits ancestraux générés par Stable Diffusion.','Stable Diffusion, ElevenLabs, Premiere Pro',    'hybrid',TRUE, TRUE, FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'valentina.cruz@email.com',     'MAI-2026-10050','Signal Inca',               'Inca Signal',               'Espagnol',  'SF, Histoire',        'Des archéologues péruviens découvrent que les quipus incas étaient un réseau de communication IA précolombien.',        'Peruvian archaeologists discover that Inca quipus were a pre-Columbian AI communication network.',          'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10050/video-test.mp4',412,'Reconstructions animées de civilisation inca via IA générative.','Sora, Midjourney v6, Final Cut Pro',             'hybrid',TRUE, FALSE,TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'ahmad.karimi@email.com',       'MAI-2026-10051','Shiraz Dreams',             'Shiraz Dreams',             'Persan',    'Poésie, Expérimental','Un poète iranien nourrit une IA avec tout le corpus de Rumi et Hafez pour engendrer un cinema-poème en persan moderne.','An Iranian poet feeds an AI the entire corpus of Rumi and Hafez to generate a film-poem in modern Persian.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10051/video-test.mp4',256,'Visuels orientaux full IA, voix poétique ElevenLabs.',        'Midjourney v6, ElevenLabs, TouchDesigner',       'full', TRUE, TRUE, TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'brigitte.lefevre@email.com',   'MAI-2026-10052','Bruges Eternelle',          'Eternal Bruges',            'Français',  'Drame, Histoire',     'Une restauratrice d\'art brugeoise utilise une IA pour voir les tableaux de Van Eyck en mouvement comme au 15e siècle.','A Bruges art restorer uses AI to see Van Eyck paintings move as they would have in the 15th century.',      'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10052/video-test.mp4',377,'Animation de tableaux flamands via IA, voix d\'époque générées.','Runway Gen-3, ElevenLabs, DaVinci Resolve',      'hybrid',TRUE, TRUE, FALSE,FALSE,'in_discussion'
  UNION ALL
  SELECT 'takeshi.yamamoto@email.com',   'MAI-2026-10053','Oni Garden',                'Oni Garden',                'Japonais',  'Animation, Horreur',  'Un jardinier de Kyoto plante des graines numériques qui font pousser des démons Oni générés par IA dans son jardin zen.','A Kyoto gardener plants digital seeds that grow AI-generated Oni demons in his zen garden.',                'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10053/video-test.mp4',299,'Animation 2D traditionnelle + Oni 3D générés, fusion unique.',  'Sora, Stable Diffusion, After Effects',          'hybrid',TRUE, FALSE,FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'chiara.ricci@email.com',       'MAI-2026-10054','Colosseo Digitale',         'Digital Colosseum',         'Italien',   'SF, Action',          'En 2055, Rome organise des gladiateurs IA dont le combat est regardé par 5 milliards de spectateurs en réalité virtuelle.','In 2055, Rome organizes AI gladiators whose combat is watched by 5 billion spectators in virtual reality.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10054/video-test.mp4',561,'Colisée reconstruit, gladiateurs full IA, spectateurs virtuels.','Sora, Runway Gen-3, ElevenLabs',                 'full', TRUE, TRUE, TRUE, TRUE, 'to_review'
  UNION ALL
  SELECT 'samuel.owusu@email.com',       'MAI-2026-10055','Ashanti Vision',            'Ashanti Vision',            'Anglais',   'Documentaire, Art',   'Un artiste ghanéen intègre l\'art Kente dans une IA qui génère des motifs textiles en réponse aux émotions des porteurs.',  'A Ghanaian artist integrates Kente art into an AI that generates textile patterns in response to wearer emotions.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10055/video-test.mp4',344,'Tissages numérisés, patterns émotionnels générés en live.',   'Stable Diffusion, TouchDesigner, Premiere Pro',  'hybrid',TRUE, FALSE,FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'mia.andersen@email.com',       'MAI-2026-10056','Midnight Sun Data',         'Midnight Sun Data',         'Finnois',   'Expérimental, Nature','Sous le soleil de minuit finlandais, des capteurs IA enregistrent la nature et composent une symphonie lumineuse.',    'Under the Finnish midnight sun, AI sensors record nature and compose a light symphony.',                    'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10056/video-test.mp4',234,'Capteurs naturels, composition IA en temps réel.',           'Stable Audio, TouchDesigner, DaVinci Resolve',   'full', FALSE,TRUE, FALSE,FALSE,'to_review'
  UNION ALL
  SELECT 'roberto.vazquez@email.com',    'MAI-2026-10057','Quetzal Code',              'Quetzal Code',              'Espagnol',  'Fantasy, SF',         'Un chamane maya guatemaltèque utilise une IA pour décoder les prophéties du calendrier maya et découvre un message futur.','A Guatemalan Maya shaman uses AI to decode Maya calendar prophecies and discovers a message from the future.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10057/video-test.mp4',453,'Jungle réelle, visions prophétiques générées par Stable Diffusion.','Stable Diffusion, ElevenLabs, After Effects',   'hybrid',TRUE, TRUE, TRUE, TRUE, 'arevoir'
  UNION ALL
  SELECT 'hana.yamada@email.com',        'MAI-2026-10058','Fuji Syntax',               'Fuji Syntax',               'Japonais',  'Art, Poésie',         'Une artiste japonaise crée 365 haïkus visuels en demandant chaque jour à une IA de représenter un poème de Matsuo Bashô.','A Japanese artist creates 365 visual haiku by asking an AI each day to represent a poem by Matsuo Basho.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10058/video-test.mp4',189,'365 images générées sur un an, montage chronologique.',      'DALL-E 3, Suno AI, DaVinci Resolve',             'full', TRUE, TRUE, FALSE,TRUE, 'to_review'
  UNION ALL
  SELECT 'jeanpierre.leblanc@email.com', 'MAI-2026-10059','Lumiere Filtree',           'Filtered Light',            'Français',  'Drame, Philosophie',  'Un philosophe en fin de vie demande à une IA de générer son autobiographie visuelle à partir de ses journaux intimes.','A philosopher at the end of his life asks an AI to generate his visual autobiography from his diaries.',    'https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10059/video-test.mp4',523,'Journaux numérisés, images générées par IA autobiographique.','Midjourney v6, ElevenLabs, Premiere Pro',        'hybrid',TRUE, TRUE, TRUE, FALSE,'to_review'
  UNION ALL
  SELECT 'amara.camara@email.com',       'MAI-2026-10060','Djembe Protocol',           'Djembe Protocol',           'Français',  'Musical, SF',         'À Bamako en 2045, un joueur de djembé crée une IA musicale qui unifie les rythmes de 54 pays africains en une seule pulsation.','In 2045 Bamako, a djembe player creates a musical AI that unifies the rhythms of 54 African countries into one pulse.','https://s3.fr-par.scw.cloud/tln/grp1/MAI-2026-10060/video-test.mp4',376,'Rythmes captés, fusion IA multi-culturelle, clips génératifs.','Suno AI, Stable Diffusion, After Effects',       'hybrid',FALSE,TRUE, FALSE,TRUE, 'to_review'
) AS f
JOIN realisator r ON r.email = f.email;
