import type { Decision, JuryFilm } from "../features/jury/types";

const DEFAULT_REALISATOR = {
    gender: null,
    firstName: "",
    lastName: "",
    birthDate: null,
    email: "",
    profession: null,
    phone: null,
    mobilePhone: null,
    street: null,
    postalCode: null,
    city: null,
    country: null,
    youtube: null,
    instagram: null,
    linkedin: null,
    facebook: null,
    xtwitter: null,
    howDidYouKnowUs: null,
    newsletter: false,
};

export const INITIAL_FILMS: JuryFilm[] = [
    {
        id: 1,
        title: "Reves de Silicium",
        author: "Lea Fontaine",
        country: "France",
        year: "2026",
        duration: "00:59.8",
        format: "MP4 1080p",
        subtitles: "FR",
        copyright: "Verifie",
        tools: "Runway ML, Sora, MusicGen",
        iaScenario: "ChatGPT-4o, Claude",
        iaImage: "Runway Gen-3, Sora",
        iaPost: "MusicGen, ElevenLabs",
        note: "Film sur la memoire humaine et l apprentissage machine. Une plongee poetique dans les strates de la conscience numerique.",
        videoUrl: null,
        myDecision: "valide",
        comments: [
            {
                id: 1,
                juryId: 1,
                name: "Marie Lefebvre",
                initials: "ML",
                profilPicture: null,
                text: "Tres belle utilisation de l IA.",
                updatedAt: "2026-01-01T00:00:00.000Z",
            },
            {
                id: 2,
                juryId: 1,
                name: "Marie Lefebvre",
                initials: "ML",
                profilPicture: null,
                text: "Rythme solide et proposition visuelle forte.",
                updatedAt: "2026-01-01T00:00:00.000Z",
            },
        ],
        opinions: [
            {
                initials: "TR",
                name: "Thomas Richard",
                badge: "like",
                comment:
                    "Traitement visuel tres original, la narration IA est parfaitement maitrisee.",
                color: "aurora",
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                badge: "discuss",
                comment: "Quelques passages trop longs, mais l ensemble est tres prometteur.",
                color: "lavande",
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                badge: "pending",
                comment: "En cours d evaluation.",
                color: "solar",
            },
        ],
        votes: [
            {
                initials: "ML",
                name: "Marie Lefebvre",
                role: "Presidente",
                decision: "valide",
                avatarVariant: 1,
            },
            {
                initials: "TR",
                name: "Thomas Richard",
                role: "Juré",
                decision: "valide",
                avatarVariant: 2,
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                role: "Juré",
                decision: "aRevoir",
                avatarVariant: 3,
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                role: "Juré",
                decision: null,
                avatarVariant: 4,
            },
        ],
        realisator: DEFAULT_REALISATOR,
    },
    {
        id: 2,
        title: "L Enfant Pixel",
        author: "Amira Ben Said",
        country: "Tunisie",
        year: "2026",
        duration: "01:02.1",
        format: "MP4 4K",
        subtitles: "FR EN",
        copyright: "Verifie",
        tools: "Pika Labs, Udio",
        iaScenario: "GPT-4o",
        iaImage: "Pika Labs 1.5",
        iaPost: "Udio, Premiere Pro",
        note: "Exploration poetique de l enfance dans un monde synthetique. Les emotions numériques rencontrent la nostalgie organique.",
        videoUrl: null,
        myDecision: "aRevoir",
        comments: [
            {
                id: 3,
                juryId: 1,
                name: "Marie Lefebvre",
                initials: "ML",
                profilPicture: null,
                text: "Tres fort esthetiquement mais fin a clarifier.",
                updatedAt: "2026-01-01T00:00:00.000Z",
            },
        ],
        opinions: [
            {
                initials: "TR",
                name: "Thomas Richard",
                badge: "like",
                comment:
                    "Visuellement epoustouflant. Le traitement de l enfance est tres touchant.",
                color: "aurora",
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                badge: "discuss",
                comment: "La fin est ambigue, a clarifier avec l autrice.",
                color: "lavande",
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                badge: "pending",
                comment: "Pas encore vu.",
                color: "solar",
            },
        ],
        votes: [
            {
                initials: "ML",
                name: "Marie Lefebvre",
                role: "Presidente",
                decision: "aRevoir",
                avatarVariant: 1,
            },
            {
                initials: "TR",
                name: "Thomas Richard",
                role: "Juré",
                decision: "valide",
                avatarVariant: 2,
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                role: "Juré",
                decision: "aRevoir",
                avatarVariant: 3,
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                role: "Juré",
                decision: null,
                avatarVariant: 4,
            },
        ],
        realisator: DEFAULT_REALISATOR,
    },
    {
        id: 3,
        title: "Memoire Vive",
        author: "Carlos Ruiz",
        country: "Espagne",
        year: "2026",
        duration: "01:28.0",
        format: "MOV 1080p",
        subtitles: "FR",
        copyright: "Verifie",
        tools: "Midjourney, ElevenLabs",
        iaScenario: "Gemini",
        iaImage: "Midjourney v6",
        iaPost: "ElevenLabs, Runway",
        note: "Transposition des souvenirs humains dans une IA narrative. Une experience unique entre memoire et algorithme.",
        videoUrl: null,
        myDecision: null,
        comments: [],
        opinions: [
            {
                initials: "TR",
                name: "Thomas Richard",
                badge: "pending",
                comment: "Pas encore visionne.",
                color: "aurora",
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                badge: "pending",
                comment: "A visionner.",
                color: "lavande",
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                badge: "like",
                comment: "Tres belle utilisation de Midjourney pour les sequences de memoire.",
                color: "solar",
            },
        ],
        votes: [
            {
                initials: "ML",
                name: "Marie Lefebvre",
                role: "Presidente",
                decision: null,
                avatarVariant: 1,
            },
            {
                initials: "TR",
                name: "Thomas Richard",
                role: "Juré",
                decision: null,
                avatarVariant: 2,
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                role: "Juré",
                decision: null,
                avatarVariant: 3,
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                role: "Juré",
                decision: "valide",
                avatarVariant: 4,
            },
        ],
        realisator: DEFAULT_REALISATOR,
    },
    {
        id: 4,
        title: "Frontieres Douces",
        author: "Omar Diallo",
        country: "Senegal",
        year: "2026",
        duration: "01:30.0",
        format: "MP4 1080p",
        subtitles: "FR",
        copyright: "A verifier",
        tools: "Suno AI, ElevenLabs",
        iaScenario: "Mistral",
        iaImage: "Aucun",
        iaPost: "Suno AI, ElevenLabs",
        note: "Experience sonore immersive sur les frontieres culturelles. Le son comme frontiere et comme pont.",
        videoUrl: null,
        myDecision: "refuse",
        comments: [
            {
                id: 4,
                juryId: 1,
                name: "Marie Lefebvre",
                initials: "ML",
                profilPicture: null,
                text: "Ne correspond pas assez aux criteres image IA.",
                updatedAt: "2026-01-01T00:00:00.000Z",
            },
        ],
        opinions: [
            {
                initials: "TR",
                name: "Thomas Richard",
                badge: "pending",
                comment: "Critique en cours.",
                color: "aurora",
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                badge: "discuss",
                comment: "Manque d image IA, critere non rempli selon le reglement.",
                color: "lavande",
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                badge: "pending",
                comment: "A evaluer.",
                color: "solar",
            },
        ],
        votes: [
            {
                initials: "ML",
                name: "Marie Lefebvre",
                role: "Presidente",
                decision: "refuse",
                avatarVariant: 1,
            },
            {
                initials: "TR",
                name: "Thomas Richard",
                role: "Juré",
                decision: null,
                avatarVariant: 2,
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                role: "Juré",
                decision: "refuse",
                avatarVariant: 3,
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                role: "Juré",
                decision: null,
                avatarVariant: 4,
            },
        ],
        realisator: DEFAULT_REALISATOR,
    },
    {
        id: 5,
        title: "Signal Perdu",
        author: "Aya Tanaka",
        country: "Japon",
        year: "2026",
        duration: "01:00.0",
        format: "MP4 1080p",
        subtitles: "FR",
        copyright: "Verifie",
        tools: "Pika Labs, Udio",
        iaScenario: "GPT-4o",
        iaImage: "Pika Labs",
        iaPost: "Udio",
        note: "Un signal emerge du bruit numerique et reconstruit une ville. Architecture generative et poesie numerique.",
        videoUrl: null,
        myDecision: null,
        comments: [],
        opinions: [
            {
                initials: "TR",
                name: "Thomas Richard",
                badge: "like",
                comment: "Concept tres fort. La reconstruction de la ville est hypnotique.",
                color: "aurora",
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                badge: "pending",
                comment: "En cours de visionnage.",
                color: "lavande",
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                badge: "pending",
                comment: "A voir.",
                color: "solar",
            },
        ],
        votes: [
            {
                initials: "ML",
                name: "Marie Lefebvre",
                role: "Presidente",
                decision: null,
                avatarVariant: 1,
            },
            {
                initials: "TR",
                name: "Thomas Richard",
                role: "Juré",
                decision: "valide",
                avatarVariant: 2,
            },
            {
                initials: "SB",
                name: "Sophie Bernard",
                role: "Juré",
                decision: null,
                avatarVariant: 3,
            },
            {
                initials: "PD",
                name: "Pierre Dubois",
                role: "Juré",
                decision: null,
                avatarVariant: 4,
            },
        ],
        realisator: DEFAULT_REALISATOR,
    },
];

export const DECISION_LABEL: Record<Exclude<Decision, null>, string> = {
    valide: "Valide",
    aRevoir: "A revoir",
    refuse: "Refuse",
    discuter: "A discuter",
};

export const DECISION_CHIP_CLASS: Record<Exclude<Decision, null>, string> = {
    valide: "bg-aurora/12 text-aurora",
    aRevoir: "bg-solar/12 text-solar",
    refuse: "bg-coral/12 text-coral",
    discuter: "bg-lavande/12 text-lavande",
};
